Upgrade JGit to 4.5 to prevent NoSuchMethodError (#12)
SMAGit was using ObjectReader.release(). This has been removed in favor of ObjectReader.close().
Also, simplify the pull request builder logic to only detect the prTargetBranch to determine if a build should use pr logic.

Resolves #11